spring:
  devtools:
    restart:
      additional-paths:
        src/main/java/com/boot
      exclude: application.yml
yml:
  address: 127.0.0.1
  staticPro:
    id: 1
    name: user
  externalPros:
     - enable: true
       host: localhost
     - enable: false
       host: 192.168.0.11